fracking_tools/document_utilities/urls.py
from django.conf.urls import url
from . import views
from document_comparison.views import document_comparison_view, compare_documents_view
from document_tagging.views import document_tagging_view, tag_documents_view, ner_tagging_view, tag_ner_view
from document_stats.views import document_stats_view, analyze_documents_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'document_utilities'

urlpatterns = [
    url(r'^$', views.document_utilities_view, name='docutils'),
    url(r'^document-comparison/$', document_comparison_view, name='doccomp'),
    url(r'^document-comparison/compare-documents/$', compare_documents_view, name='compdocs'),
    url(r'^document-keywords-tagging/$', document_tagging_view, name='doctag'),
    url(r'^document-keywords-tagging/tag-documents-keywords/$', tag_documents_view, name='tagdocs'),
    url(r'^document-ner-tagging/$', ner_tagging_view, name='nertag'),
    url(r'^document-ner-tagging/tag-documents-ner/$', tag_ner_view, name='tagner'),
    url(r'^document-statistics/$', document_stats_view, name='docstats'),
    url(r'^document-statistics/compute-document-statistics/$', analyze_documents_view, name='statdocs'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/fracking_tools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^network-utilities/', include('network_builder.urls', namespace='network_builder')),
    url(r'^document-utilities/', include('document_utilities.urls', namespace='document_utilities')),
    url(r'^$', include('home.urls', namespace='home'), name='home'),
]

fracking_tools/home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^', views.index, name='index'),
]

fracking_tools/templates/document_tagging_keywords/alerts.html
<div id="empty-fields-alert" class="alert alert-danger alert-dismissible fade show" role="alert">
  <i class="fa fa-times-circle" aria-hidden="true"></i> You must upload at least <strong>1</strong> file to tag, upload/enter a list of keywords and choose an output .zip name!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

fracking_tools/templates/document_tagging_keywords/jumbotron.html
<div class="jumbotron jumbotron-fluid" id="home-banner">
  <div class="container text-center">
    <h1 class="display-4 text-dark">Fracking Tools: Tag Documents for Keywords</h1>
    <p class="lead text-dark">Tag one or many documents for a list of keywords.</p>
    <hr class="my-4">
    <div class="row my-4">
      <div class="col-sm-3">
        <a href="{% url 'document_utilities:doccomp' %}" class="btn btn-primary btn-block my-1">Compare Documents</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'document_utilities:nertag' %}" class="btn btn-success btn-block my-1">Tag Documents with NER</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'document_utilities:docstats' %}" class="btn btn-danger btn-block my-1">Compute Document Statistics</a>
      </div>
      <div class="col-sm-3">
        <a href="#" class="btn btn-dark btn-block my-1">OCR Documents</a>
      </div>
    </div>
  </div>
</div>

fracking_tools/templates/document_tagging_keywords/steps.html
<div class="card w-100 my-4 border-warning">
  <div class="card-body text-left">
    <h4 class="card-title mb-4">0. Before You Begin</h4>
    <p class="card-text">
      Before tagging documents you <strong>MUST</strong> follow the exact instructions provided below.
    </p>
  </div>
  <div class="card-footer">
    <div class="text-center">
      <button class="btn btn-warning btn-block" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="fa fa-info-circle" aria-hidden="true"></i> Instructions</button>
    </div>
  </div>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Instructions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-left">
        <p>1. Select all the files you want to tag. Your files must be <strong>.txt</strong> or <strong>.docx</strong>.</p>
        <p>2. Upload a file or enter a list of keywords to tag each document.</p>
        <p>- If you choose to upload a file with keywords: each keyword must be separated with commas.</p>
        <p> &nbsp;&nbsp;&nbsp;&nbsp; For example: keyword1,keyword2,keyword3, etc.</p>
        <p>- To manually enter keywords, click on <kbd>Manually Input Keywords</kbd>. Each keyword must be separated with commas.</p>
        <p>- You can toggle between <strong>Manually Input Keywords</strong> and <strong>Input Keywords from File</strong> by clicking
        on <kbd>Manually Input Keywords</kbd> or <kbd>Input Keywords from File</kbd>.

        <p>
          3. Once you choose which files to upload and enter an output <strong>.zip</strong>
          name, you can click on <kbd>Tag <i class="fa fa-tags" aria-hidden="true"></i></kbd> to tag your files for keywords.
        </p>
        <p>
          4. The output zip file will contain <strong>.docx</strong> documents where the heading
          is a list of the keywords that were found in each document. Additionally, each tagged
          document will have the found keywords capitalized and boldened for easier lookup.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<form id="tag-files-form" action="{% url 'document_utilities:tagdocs' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="card w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">1. Upload Documents to Tag</h4>
      <p class="card-text">
        Upload the files you want to tag. Valid file formats are <strong>.txt</strong>, and <strong>.docx</strong>.
      </p>
    </div>
    <div class="card-footer">
      <div class="text-center">
        <input class="form-control" type="file" id="tag-documents" name="tag-documents" accept=".txt,.docx" multiple required>
      </div>
    </div>
  </div>
  <div class="card mb-4 w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">2. Upload or Enter a list of keywords</h4>
      <p>
        <button type="button" class="btn btn-dark w-100" onclick="keywordEntryHandler(this);">
        Manually Input Keywords
        </button>
      </p>
    </div>
    <input type="hidden" id="keywords-type" name="keywords-type" value="file">

    <div class="card-footer invisible" id="manual-keywords">
      <p class="text-left">
        Enter a list of keywords separated by commas
      </p>
      <div class="text-center">
        <input class="form-control" type="text" id="manual-keyword-list" name="manual-keyword-list" placeholder="e.g. word 1, word 2, word 3" required>
      </div>
    </div>
    <div class="card-footer" id="file-keywords">
      <p class="text-left">
        Upload a list of keywords from file
      </p>
      <div class="text-center">
        <input class="form-control" type="file" id="file-keyword-list" name="file-keyword-list" accept=".txt" required>
      </div>
    </div>
  </div>
  <div class="card mb-4 w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">3. Choose a Name for the Output <strong>.zip</strong> File</h4>
      <p class="card-text">
        Enter the output .zip name without a file extension.
      </p>
    </div>
    <div class="card-footer">
      <div class="text-center">
        <input class="form-control" type="text" id="output-zip-name" name="output-zip-name" placeholder="Enter a .zip name" required>
      </div>
    </div>
  </div>
  <div class="card mb-4 w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">4. Tag Documents</h4>
    </div>
    <div class="card-footer">
      <div class="text-center">
        <button type="button" onclick="submit_form();" class="btn btn-dark btn-block" name="button">Tag <i class="fa fa-tags" aria-hidden="true"></i></button>
      </div>
    </div>
  </div>
</form>