fracking_tools/document_utilities/urls.py
from django.conf.urls import url
from . import views
from document_comparison.views import document_comparison_view, compare_documents_view
from document_tagging.views import document_tagging_view, tag_documents_view, ner_tagging_view, tag_ner_view
from document_stats.views import document_stats_view, analyze_documents_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'document_utilities'

urlpatterns = [
    url(r'^$', views.document_utilities_view, name='docutils'),
    url(r'^document-comparison/$', document_comparison_view, name='doccomp'),
    url(r'^document-comparison/compare-documents/$', compare_documents_view, name='compdocs'),
    url(r'^document-keywords-tagging/$', document_tagging_view, name='doctag'),
    url(r'^document-keywords-tagging/tag-documents-keywords/$', tag_documents_view, name='tagdocs'),
    url(r'^document-ner-tagging/$', ner_tagging_view, name='nertag'),
    url(r'^document-ner-tagging/tag-documents-ner/$', tag_ner_view, name='tagner'),
    url(r'^document-statistics/$', document_stats_view, name='docstats'),
    url(r'^document-statistics/compute-document-statistics/$', analyze_documents_view, name='statdocs'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/fracking_tools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^network-utilities/', include('network_builder.urls', namespace='network_builder')),
    url(r'^document-utilities/', include('document_utilities.urls', namespace='document_utilities')),
    url(r'^$', include('home.urls', namespace='home'), name='home'),
]

fracking_tools/home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^', views.index, name='index'),
]

fracking_tools/document_comparison/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse

from utils.files import ExtensionHandler
from utils.document_comparison import compair

import os
import re
import csv


def clean_text(s):
    return ' '.join(' '.join(re.findall(r'[a-zA-Z0-9]+', s)).split())


def document_comparison_view(request):
    context = {}
    return render(request, 'document_comparison/document_comparison.html', context)


def compare_documents_view(request):
    if request.method == 'POST':
        documents = request.FILES.getlist('comparison-documents')

        results = []

        for i in xrange(len(documents)):
            for j in xrange(i + 1, len(documents)):

                content1, content2 = ExtensionHandler(documents[i]).get_content(), ExtensionHandler(documents[j]).get_content()
                documents[i].seek(0)
                documents[j].seek(0)

                try:
                    result = [documents[i].name, documents[j].name] + compair(content1, content2)
                    results.append(result)
                except Exception as e:
                    print "Error: ", e
                    result = [documents[i].name, documents[j].name, 'Error', 'Error']
                    results.append(result)

        fs = FileSystemStorage()
        output_csv_path = "{0}.csv".format(os.path.join(fs.location, clean_text(request.POST.get('comparison-output-csv-name'))))

        header = ['File A', 'File B', 'Cosine Similarity', 'Jaccard Similarity']

        with open(output_csv_path, 'wb') as csv_file:
            writer = csv.writer(csv_file, delimiter=str(u',').encode('utf-8'))
            writer.writerow(header)
            for result in results:
                writer.writerow(result)

        with open(output_csv_path, 'rb') as csv_file:
            response = HttpResponse(csv_file.read())
            response['content_type'] = 'text/csv'
            response['Content-Disposition'] = 'attachment; filename="{0}"'.format(os.path.split(output_csv_path)[1])
        return response
    return redirect('document_utilities:doccomp')

fracking_tools/templates/document_comparison/alerts.html
<div id="networks-built-alert" class="alert alert-success alert-dismissible fade show" role="alert">
  <i class="fa fa-check" aria-hidden="true"></i> <strong><span id="number-of-files"></span></strong> files were compared successfully!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div id="empty-fields-alert" class="alert alert-danger alert-dismissible fade show" role="alert">
  <i class="fa fa-times-circle" aria-hidden="true"></i> You must select at least <strong>2</strong> files and choose an output .csv name!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

fracking_tools/templates/document_comparison/document_comparison.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>Fracking Tools: Document Utilities > Compare Documents</title>
    {% include 'global/head.html' %}
  </head>
  <body>
    {% include 'global/navbar.html' %}
    <div id="wrapper">
      <div id="header">
        {% include 'document_comparison/jumbotron.html' %}
      </div>
      <div id="content">
        <div class="container text-center">
          {% include 'document_comparison/alerts.html' %}
          {% include 'document_comparison/steps.html' %}
        </div>
      </div>
      <div id="footer">
        {% include 'global/footer.html' %}
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="{% static 'document_comparison/js/main.js' %}" charset="utf-8"></script>
  </body>
</html>

fracking_tools/templates/document_comparison/jumbotron.html
<div class="jumbotron jumbotron-fluid" id="home-banner">
  <div class="container text-center">
    <h1 class="display-4 text-dark">Fracking Tools: Compare Documents</h1>
    <p class="lead text-dark">Compare one pair or many pairs of documents for content or textual similarity.</p>
    <hr class="my-4">
    <div class="row my-4">
      <div class="col-sm-3">
        <a href="{% url 'document_utilities:doctag' %}" class="btn btn-primary btn-block my-1">Tag Documents for Keywords</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'document_utilities:nertag' %}" class="btn btn-success btn-block my-1">Tag Documents with NER</a>
      </div>
      <div class="col-sm-3">
        <a href="{% url 'document_utilities:docstats' %}" class="btn btn-danger btn-block my-1">Compute Document Statistics</a>
      </div>
      <div class="col-sm-3">
        <a href="" class="btn btn-dark btn-block my-1">OCR Documents</a>
      </div>
    </div>
  </div>
</div>

fracking_tools/templates/document_comparison/steps.html
<div class="card w-100 my-4 border-warning">
  <div class="card-body text-left">
    <h4 class="card-title mb-4">0. Before You Begin</h4>
    <p class="card-text">
      Before comparing documents you <strong>MUST</strong> follow the exact instructions provided below.
    </p>
  </div>
  <div class="card-footer">
    <div class="text-center">
      <button class="btn btn-warning btn-block" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="fa fa-info-circle" aria-hidden="true"></i> Instructions</button>
    </div>
  </div>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Instructions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-left">
        <p>1. Select all the files you want to compare. Your files must be <strong>.txt</strong> or <strong>.docx</strong>.</p>
        <p>2. Choose a name for the results file. The results of the file comparisons will be outputted to a single <strong>.csv</strong> file.</p>

        <p>
          3. Once you choose which files to upload and enter an output <strong>.csv</strong>
          name, you can click on <kbd>Compare <i class="fa fa-exchange" aria-hidden="true"></i></kbd> to compare your files.
        </p>
        <p>
          4. The output file will look something like this
          <table class="table">
            <thead>
              <th>File A</th>
              <th>File B</th>
              <th>Cosine Similarity</th>
              <th>Jaccard Similarity</th>
            </thead>
            <tr>
              <td>Example File A.txt</td>
              <td>Example File B.txt</td>
              <td>0.5</td>
              <td>0.6</td>
            </tr>
            <tr>
              <td>Example File A.txt</td>
              <td>Example File D.txt</td>
              <td>0.8</td>
              <td>0.4</td>
            </tr>
            <tr>
              <td>Example File A.txt</td>
              <td>Example File F.txt</td>
              <td>0.3</td>
              <td>0.0</td>
            </tr>
          </table>
        </p>
        <hr>
        <h6 class="text-center">Some Background Information</h6><br>
        <p><strong>Cosine Similarity </strong> refers to comparing the content
          of two or more documents. The cosine similarity of two documents ranges from -1 to +1. If two documents
          talk about the same topics their cosine similarity is closer to +1. If two documents talk about completely
          opposite topics, their cosine similarity is closer to -1. However, if two documents are unrelated,
          their cosine similarity is exactly 0.
        </p>
        <p>
          This comparison is possible thanks to the <strong>Vector Space Model (VSM)</strong>.
          VSM is an algebraic model representing textual information as a vector.
          The components of this vector are important-word frequencies determined using the term
          frequency-inverse document frequency <a href="http://en.wikipedia.org/wiki/Tf%E2%80%93idf">(tf-idf)</a> method.
        </p>
        <p>
          <strong>Jaccard Similarity </strong> is used to detect whether two documents are almost identical.
          This method reduces a document to a set of strings through a process called shingling.
          Shingling extracts the set of all substrings of length k (k-shingles) from a text. This is implemented
          by sliding a window of size k over each document--character by character--and putting the substrings into a set.
          For example, the document "abcabcac" yields the 3 shingles {"abc", "bca", "cab", "cac"}. This set eliminates duplicate shingles.
        </p>
        <p>
          Once documents have been turned into shingle sets, the jaccard similarity of 2 sets (2 documents) is calculated
          by dividing the size of the intersection of two sets by the size of their union. In other words, the ratio of the number
          of words that are found in BOTH documents and the total number of unique words in BOTH documents.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<form id="events-form" action="{% url 'document_utilities:compdocs' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="card w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">1. Upload Documents to Compare</h4>
      <p class="card-text">
        Upload the files you want to compare. Valid file formats are <strong>.txt</strong>, and <strong>.docx</strong>.
      </p>
    </div>
    <div class="card-footer">
      <div class="text-center">
        <input class="form-control" type="file" name="comparison-documents" accept=".txt,.pdf,.docx" multiple required>
      </div>
    </div>
  </div>
  <div class="card mb-4 w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">2. Choose a Name for the Output <strong>.csv</strong> File</h4>
      <p class="card-text">
        Enter the output .csv name without a file extension.
      </p>
    </div>
    <div class="card-footer">
      <div class="text-center">
        <input class="form-control" type="text" name="comparison-output-csv-name" placeholder="Enter a .csv name" required>
      </div>
    </div>
  </div>
  <div class="card mb-4 w-100 my-4">
    <div class="card-body text-left">
      <h4 class="card-title mb-4">3. Compare Documents</h4>
    </div>
    <div class="card-footer">
      <div class="text-center">
        <button type="button" onclick="submit_form();" class="btn btn-dark btn-block" name="button">Compare <i class="fa fa-exchange" aria-hidden="true"></i></button>
      </div>
    </div>
  </div>
</form>