fracking_tools/document_utilities/urls.py
from django.conf.urls import url
from . import views
from document_comparison.views import document_comparison_view, compare_documents_view
from document_tagging.views import document_tagging_view, tag_documents_view, ner_tagging_view, tag_ner_view
from document_stats.views import document_stats_view, analyze_documents_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'document_utilities'

urlpatterns = [
    url(r'^$', views.document_utilities_view, name='docutils'),
    url(r'^document-comparison/$', document_comparison_view, name='doccomp'),
    url(r'^document-comparison/compare-documents/$', compare_documents_view, name='compdocs'),
    url(r'^document-keywords-tagging/$', document_tagging_view, name='doctag'),
    url(r'^document-keywords-tagging/tag-documents-keywords/$', tag_documents_view, name='tagdocs'),
    url(r'^document-ner-tagging/$', ner_tagging_view, name='nertag'),
    url(r'^document-ner-tagging/tag-documents-ner/$', tag_ner_view, name='tagner'),
    url(r'^document-statistics/$', document_stats_view, name='docstats'),
    url(r'^document-statistics/compute-document-statistics/$', analyze_documents_view, name='statdocs'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/fracking_tools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^network-utilities/', include('network_builder.urls', namespace='network_builder')),
    url(r'^document-utilities/', include('document_utilities.urls', namespace='document_utilities')),
    url(r'^$', include('home.urls', namespace='home'), name='home'),
]

fracking_tools/home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^', views.index, name='index'),
]

fracking_tools/network_builder/urls.py
from django.conf.urls import url
from . import views
from network_comparison.views import network_comparison_view, compare_networks_view

from django.conf import settings
from django.conf.urls.static import static

app_name = 'network_builder'

urlpatterns = [
    url(r'^$', views.network_builder_view, name='network_builder'),
    url(r'^build-networks-from-events/$', views.events_network_view, name='events'),
    url(r'^build-networks-from-events/build/$', views.build_event_networks, name='build_enet'),
    url(r'^build-networks-from-pairs/$', views.pairs_network_view, name='pairs'),
    url(r'^build-networks-from-pairs/build/$', views.build_pair_networks, name='build_pnet'),
    url(r'^compare-networks/$', network_comparison_view, name='netcomp'),
    url(r'^compare-networks/compare/$', compare_networks_view, name='compnets'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fracking_tools/templates/global/footer.html
<div class="container text-center">
  <div class="row">
    <div class="col-sm-6">
      <i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:rahuezo@ucdavis.edu">rahuezo@ucdavis.edu</a>
    </div>
    <div class="col-sm-6">
      <i class="fa fa-globe" aria-hidden="true"></i> <a href="http://rudyhuezo.work">rudyhuezo.work</a>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-sm-12 text-center text-muted">
      <p class="lead">
        <i class="fa fa-code" aria-hidden="true"></i> with <i class="fa fa-heart" aria-hidden="true"></i> by <strong>Rudy Huezo</strong>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 text-muted">
      © 2017 Fracking Tools All rights reserved.
    </div>
  </div>
</div>

fracking_tools/templates/global/head.html
{% load static %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

<!-- Font Awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<!-- Local CSS -->
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">

<!-- Site Favicon -->
<link rel="shortcut icon" type="image/png" href="{% static 'home/img/fracking-tools logo.png' %}"/>

fracking_tools/templates/global/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark navbar-bg-custom sticky-top">
  <a class="navbar-brand" href="{% url 'home:index' %}">
    <img src="{% static 'home/img/fracking-tools logo.png' %}" alt="">
    Fracking Tools
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mr-2 text-center">
      <li class="nav-item m-2 dropdown">
        <a class="btn btn-primary dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Network Utilities
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'network_builder:events' %}">Build Networks from Events</a>
          <a class="dropdown-item" href="{% url 'network_builder:pairs' %}">Build Networks from Individual Pairs</a>
          <a class="dropdown-item" href="{% url 'network_builder:netcomp' %}">Compare Networks</a>
        </div>
      </li>
      <li class="nav-item m-2 dropdown">
        <a class="btn btn-light dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Document Utilities
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'document_utilities:doccomp' %}">Compare Documents</a>
          <a class="dropdown-item" href="{% url 'document_utilities:doctag' %}">Tag Documents for Keywords</a>
          <a class="dropdown-item" href="{% url 'document_utilities:nertag' %}">Tag Documents Using NER</a>
          <a class="dropdown-item" href="{% url 'document_utilities:docstats' %}">Compute Document Statistics</a>
          <a class="dropdown-item blurred" href="">OCR Documents</a>
        </div>
      </li>
    </ul>
  </div>
</nav>